apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosodigitalgoodsapp
spec:
  replicas: 1
  selector:
   matchLabels:
    app: contosodigitalgoodsapp
  template:
    metadata:
      labels:
        app: contosodigitalgoodsapp
    spec:
      containers:
        - name: contosodigitalgoodsapp
          image: contosogoodsacr73200.azurecr.io/contoso/digitalgoods/application
          ports:
            - containerPort: 80
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: contosodigitalgoods
spec:
  replicas: 1
  selector:
   matchLabels:
    app: contosodigitalgoods
  template:
    metadata:
      labels:
        app: contosodigitalgoods
    spec:
      containers:
        - name: contosodigitalgoods
          image: contosogoodsacr73200.azurecr.io/contoso/digitalgoods/tokenservice
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: contosodigitalgoodsapp
spec:
    type: LoadBalancer
    ports:
        - port: 80
    selector:
        app: contosodigitalgoodsapp
---
apiVersion: v1
kind: Service
metadata:
    name: contosodigitalgoods
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: contosodigitalgoods