apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: abtoptionbdigoods 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: abtoptionbdigoods 
    spec:
      containers:
        - name: abtoptionbdigoods 
          image: contosodigitalgood.azurecr.io/abtoptionbdigoods
          ports:
          - containerPort: 80