# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:

- PlanB-DigitalGoods
resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'contosodigitalgood'
  imageRepository_app: 'contosodigitalgoodsapp-ne'
  imageRepository_token: 'contosodigitalgoods-ne'
  containerRegistry: 'contosodigitalgood.azurecr.io'
  
  #dockerfilePath: '**/Dockerfile'
  
  tag: '$(Build.BuildId)'
  imagePullSecret: 'contosodigitalgood-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
  # Name of the new namespace being created to deploy the PR changes.
  k8sNamespaceForPR: 'default'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an Application API image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository_app)
        buildContext : '$(Build.Repository.LocalPath)/src'
        dockerfile: '$(Build.SourcesDirectory)/src/Contoso.DigitalGoods.Application.API/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Build and push an Token API image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository_token)
        buildContext : '$(Build.Repository.LocalPath)/src'
        dockerfile: '$(Build.SourcesDirectory)/src/Contoso.DigitalGoods.TokenService.API/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'TradableDigitalAsset-1582.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository_app):$(tag)
                $(containerRegistry)/$(imageRepository_token):$(tag)

 
