apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: contosodigitalgoods
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contosodigitalgoods
    spec:
      containers:
        - name: contosodigitalgoods
          image: contosodigitalgood.azurecr.io/contosodigitalgoods
          ports:
          - containerPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contosodigitalgoodsapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contosodigitalgoodsapp
    spec:
      containers:
        - name: contosodigitalgoodsapp
          image: contosodigitalgood.azurecr.io/contosodigitalgoodsapp
          ports:
            - containerPort: 80