apiVersion: v1
kind: Service
metadata:
    name: contosodigitalgoods-ne
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: contosodigitalgoods-ne
---
apiVersion: v1
kind: Service
metadata:
    name: contosodigitalgoodsapp-ne
spec:
    type: LoadBalancer
    ports:
        - port: 80
    selector:
        app: contosodigitalgoodsapp-ne