apiVersion: v1
kind: Service
metadata:
    name: contosodigitalgoods
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: contosodigitalgoods
---
apiVersion: v1
kind: Service
metadata:
    name: contosodigitalgoodsapp
spec:
    type: LoadBalancer
    ports:
        - port: 80
    selector:
        app: contosodigitalgoodsapp